### PR TITLE
feat: Add support for gists

### LINKED ISSUE #5: [Feature Request]  Support GitHub Gists
Would be nice if this project add support for GitHub Gist as well e.g. https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13

### PR DESCRIPTION
**Pull request by qoomon**
Fixes #5 

This will allow generating sparklines for gist like https://stars.medv.io/gist:qoomon/5dfcdf8eec66a051ecd85625518cfd13

### CODE REVIEW

**Comment by antonmedv** [comment]
Cool 👌🏻

**Comment by qoomon** [comment]
Just a note for potential future feature to gather all stars for an owner #4 .

This query will iterate get all repositories and gists for an owner. Then we just need to call `fetchStargazerDates` for every repo and gist and merge results.

```grapql
query ($owner: String!, $repositoriesEndCursor: String, $gistsEndCursor: String) {
  user(login: $owner) {
    repositories(first: 100, after: $repositoriesEndCursor) {
      nodes {
        name
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
    gists(first: 100, after: $gistsEndCursor) {
      nodes {
        name
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
  rateLimit {
    remaining
  }
}
```

**Comment by antonmedv** [comment]
Way to mane errors: 
```
0|spark    | /home/anton/stars.medv.io/render.js:30
0|spark    |     const svg = createSvg(dates)
0|spark    |     ^^^^^
0|spark    | 
0|spark    | SyntaxError: Unexpected token 'const'
0|spark    |     at internalCompileFunction (node:internal/vm:73:18)
0|spark    |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
0|spark    |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
0|spark    |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|spark    |     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|spark    |     at Module._load (node:internal/modules/cjs/loader:960:12)
0|spark    |     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|spark    |     at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|spark    |     at require (node:internal/modules/cjs/helpers:121:18)
0|spark    |     at Object.<anonymous> (/home/anton/stars.medv.io/index.js:7:28)


0|spark  | {"errors":[{"extensions":{"value":null,"problems":[{"path":[],"explanation":"Expected value to not be null"}]},"locations":[{"line":2,"column":9}],"message":"Variable $owner of type String! was provided invalid value"},{"extensions":{"value":null,"problems":[{"path":[],"explanation":"Expected value to not be null"}]},"locations":[{"line":2,"column":26}],"message":"Variable $name of type String! was provided invalid value"}]}
```

**Comment by qoomon** [comment]
My bad I'll fix it I pushed a wrong version

**Pull request merged**
