### PR TITLE
feat: Add support for gists

### PR DESCRIPTION
**Pull request by qoomon**
This time I've tested everything is working :-) (shame on me for #6)

This PR will add support for gist stargazers e.g. https://stars.medv.io/qoomon/gist:5dfcdf8eec66a051ecd85625518cfd13.svg

- `render.js`
  - add gist support 
- `api.js`
  - move `rateLimit` in graphQL queries (`render.js`) to `api.js` by reading limits from response header (recommended way by GitHub API docs)
  - replace `r2` package with `node-fetch` package
- `svg.js`
  - refactor parameter to array of `Date` objects instead of epoch timestamp

### CODE REVIEW

**Comment by antonmedv** [comment]
Please deploy your version, so I can test my self

**Comment by qoomon** [comment]
Where should I deploy? Or just anywhere?

**Comment by antonmedv** [comment]
Just anywhere

**Comment by qoomon** [comment]
feel free to test http://ec2-3-72-47-194.eu-central-1.compute.amazonaws.com

**Comment by antonmedv** [comment]
Looks stuck at http://ec2-3-72-47-194.eu-central-1.compute.amazonaws.com/
image
image

**Comment by antonmedv** [comment]
Also I don't like hot a title for gists are shown .

image

**Comment by antonmedv** [comment]
Maybe we should have a separate url for gists? gist.stars.medv.io?

**Comment by qoomon** [comment]
You have used a wrong url pattern you need to use it like this `<baseUrl>/<owner>/gist:<gistHash>`
e.g. http://ec2-3-72-47-194.eu-central-1.compute.amazonaws.com/qoomon/gist:5dfcdf8eec66a051ecd85625518cfd13

**Comment by antonmedv** [comment]
This is my point. This is very unintuitive what this sort support gists as well. So we can somehow highlight this in ui. Or maybe deploy at a separate url and name it Gist Sparklines?

**Comment by qoomon** [comment]
Or what about following convention?
- `<baseUrl>/<owner>/<repoName>`
- `<baseUrl>/gist/<owner>/<gistHash>`
- or back to the initial idea `<baseUrl>/gist:<owner>/<gistHash>`

 I thinks repos(files and directories repos) and gist (file only repos) are so alike that is seems odd to have two deployments for that

**Comment by qoomon** [comment]
At least every thing is now working as expected, I fixed all issues.

**Comment by qoomon** [comment]
I've deployed a version with the initial url pattern `<baseUrl>/gist:<owner>/<gistHash>`

see http://ec2-3-72-47-194.eu-central-1.compute.amazonaws.com/gist:qoomon/5dfcdf8eec66a051ecd85625518cfd13

I think this is the most appealing variant

**Comment by antonmedv** [comment]
Super! Now it looks more cool. 

One more thing. Lets get name of the gist from GraphQL api. 

image

And use it here:
image

How difficult it will be to implement?

**Comment by qoomon** [comment]
Unfortunately it would be a complete refactoring. 
The header always shows the name of the first file (even if there a multiple files in one gist)
And just an extra note <username>/<firstFileName> is not guaranteed to be unique for a user.

**Comment by antonmedv** [comment]
I mean we can still use sha1, but only display name in the title. This will require saving gist names locally?

**Comment by qoomon** [comment]
I'd suggest that we release this version first, and then we add the gist display name later.
> This will require saving gist names locally?

Yes that would be one option.
Another option would be to call `fetch('https://api.github.com/gists/<gistHash>')` and resolve name on the fly

**Comment by qoomon** [comment]
I've implemented the gist display name, see 
http://ec2-3-72-47-194.eu-central-1.compute.amazonaws.com/gist:qoomon/5dfcdf8eec66a051ecd85625518cfd13

**Comment by qoomon** [comment]
WDYT?

**Comment by qoomon** [comment]
@antonmedv can we merge it so I can stop my instance again?

**Comment by antonmedv** [comment]
Will try to take a look tonight and deploy.

**Comment by qoomon** [comment]
@antonmedv do you still need the server? I'd like to shut it down.

**Comment by antonmedv** [comment]
No, you can shut it down.

**Comment by qoomon** [comment]
cool, looking forward to the merge and release

**Comment by qoomon** [comment]
@antonmedv can you estimate when you will merge this feature?

**Comment by antonmedv** [comment]
Sometime soon?... There is no SLO, so you get it -)))

**Comment by qoomon** [comment]
👀

**Comment by qoomon** [comment]
🥺

**Comment by antonmedv** [comment]
Still didn’t find any time. Will try tonight.

**Comment by qoomon** [comment]
🥺

**Comment by qoomon** [comment]
Is there any rough estimation of a release date?

**Comment by qoomon** [comment]
Can I support to get this PR to be merged?

**Comment by qoomon** [comment]
Still looking forward for a release.

**Comment by antonmedv** [comment]
Hi, yea) Got a lot of work on another project. Will try to run pr locally and will deploy.

**Comment by qoomon** [comment]
🥺

**Comment by qoomon** [comment]
>  Will try to run pr locally and will deploy.

any impediments?

**Comment by antonmedv** [comment]
Kind-a luck of time to this project right now. 

@qoomon maybe you can host own version of spark with this feature?

**Comment by qoomon** [comment]
@antonmedv unfortunately I can not, I don't have any server.

**Comment by qoomon** [comment]
@antonmedv eventually I was able to find some spare time to make your idea work without any self hosted server.

https://github.com/qoomon/starline

It utilize vercel edge functions as an api to get and cache the badges. If the badge does not exist or has expired the vercel function will trigger a github actions workflow to generate the badge asynchronously. 

thanks a lot for your project and inspiration

**Pull request closed without merging**
